### ISSUE TITLE
error 0151

### ISSUE THREAD

**Issue by LibreTitan** [MarlonColca/Atikux#1]
Cuando ejecuto el archivo de prueba da este error: 

`
EXCEPTION :/
#### [DEVELOPER]

System.ServiceModel.FaultException: -

Server stack trace:
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRunt
ime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean on
eway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan tim
eout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCall
Message methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   en Atikux.DocumentosElectronicoSunat.billService.sendBill(sendBillRequest req
uest)
   en Atikux.DocumentosElectronicoSunat.billServiceClient.Atikux.DocumentosElect
ronicoSunat.billService.sendBill(sendBillRequest request) en c:\Users\HP - PC\Do
cuments\Visual Studio 2012\Projects\Atikux\Atikux\Service References\DocumentosE
lectronicoSunat\Reference.cs:línea 277
   en Atikux.DocumentosElectronicoSunat.billServiceClient.sendBill(String fileNa
me, Byte[] contentFile) en c:\Users\HP - PC\Documents\Visual Studio 2012\Project
s\Atikux\Atikux\Service References\DocumentosElectronicoSunat\Reference.cs:línea
 284
   en Atikux.classes.SunatServices.sendDocument(String NameOfFileZip) en c:\User
s\HP - PC\Documents\Visual Studio 2012\Projects\Atikux\Atikux\classes\SunatServi
ces.cs:línea 41
#### [CLIENT]

soap-env-Server.0151
#### [/CLIENT]

`

**Comment by coins5** [comment]
Buenos días, El apartado de Developer, solo es el stack trace del origen del problema. El apartado de Client indica que es un problema detectado por Sunat. Existen 3 tipos: 
1. El que responde directamente el servidor de Sunat
2. Mediante un excepción
3. Dentro del zip de respuesta también puede venir un error

Ese error específicamente(0151) significa: 
"El nombre del archivo ZIP es incorrecto"
Según el manual de programador - Anexo 2 - Listado de errores: 
https://www.google.com.pe/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwj8iOSp1M_MAhXHth4KHfDICkgQFgggMAA&url=http%3A%2F%2Fcontenido.app.sunat.gob.pe%2Finsc%2FComprobantesDePago%2BElectronicos%2FeFacturas%2Bd%2Bsistemas%2Bcontrib%2FAct%2B04.04.2014%2FANEXO%2B2%2Blistado%2Bde%2Berrores%2B-%2BMANUAL%2BDEL%2BPROGRAMADOR.DOCX&usg=AFQjCNE2WUTyIS5lRYcriGu-ElVZ6RsKqw&sig2=5BqgD14NRrz2xxNLyD3cVw

Gracias por revisar el código! :)

**Comment by LibreTitan** [comment]
Es correcto, lo que pasa es que cuando vi tu codigo la primera vez y use la prueba pasó sin ningun problema, ahora en estos dias he vuelvo a hacer el mismo procedimiento con el mismo archivo y da ese error, algo habrá cambiado en el servidor de la SUNAT o yo me estoy equivocando en algo...

**Comment by coins5** [comment]
Si, a mi me daba error. Pero era porque la fecha estaba fuera de presentación. Para resolverlo, abrí el archivo XML y le puse una fecha mas reciente. Pero ese error en específico tal vez sea porque el nombre del archivo no coincide en lo indicado en el XML. En todo caso pásame el archivo zip que estás utilizando para revisarlo y así te digo

**Comment by SteveCampos** [comment]
Me parece lo mismo que dice @MarlonColca, lo que debe estar pasando es que el la serie + correlativo del filename, deben ser diferentes a los que pones en el XML.

**Comment by coins5** [comment]
@LibreTitan, Dime necesitas ayuda? Si ya está resuelto podemos cerrar este tema.

**Comment by LibreTitan** [comment]
Hola, gracias por el interés, como decías, con el zip de ejemplo, antes me daba el mismo error " presentado fuera de fecha" lo devolvía en un zip, ahora ahora con el mismo archivo da el error que mencionaba, podrás reproducir el error o solo será cosa mía?.

**Comment by coins5** [comment]
Adjunta el zip por aquí porfa, para poder verlo.

**Comment by SteveCampos** [comment]
LibreTitan, estos días también tuve problemas con los servicos  web - beta de la Sunat, y buscando el problema encontré que están caídos, lo puedes mirar en este mensaje. http://www.sunat.gob.pe/mensajes/mayo/2016/aviso-ti-120516.html. El mensaje dice que están 'evaluando el inconveniente' con lo poco que ayuda, Les dejaré un mensaje para saber la fecha prevista en la cual lo tendrán solucionado. A esperar :/
